/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CK1;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form v
     */
    public View() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        bangtable.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sogiosudungtextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tentextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sdttextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diachitextfield = new javax.swing.JTextField();
        thembutton = new javax.swing.JButton();
        suabutton = new javax.swing.JButton();
        xoabutton = new javax.swing.JButton();
        timkiembutton = new javax.swing.JButton();
        tinhtienbutton = new javax.swing.JButton();
        thoatbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangtable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        namradio = new javax.swing.JRadioButton();
        nuradio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Price Per Hour:5000");

        jLabel3.setFont(new java.awt.Font("SF Mono", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Quản Lí Internet");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Hours of Use:");

        sogiosudungtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sogiosudungtextfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel6.setText("Name:");

        jLabel5.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel5.setText("PhoneNumber:");

        jLabel4.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel4.setText("Address:");

        diachitextfield.setPreferredSize(new java.awt.Dimension(64, 26));

        thembutton.setText("Add");
        thembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thembuttonActionPerformed(evt);
            }
        });

        suabutton.setText("Edit");
        suabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabuttonActionPerformed(evt);
            }
        });

        xoabutton.setText("Delete");
        xoabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabuttonActionPerformed(evt);
            }
        });

        timkiembutton.setText("Search");
        timkiembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiembuttonActionPerformed(evt);
            }
        });

        tinhtienbutton.setText("Calculated");
        tinhtienbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhtienbuttonActionPerformed(evt);
            }
        });

        thoatbutton.setText("Exit");
        thoatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatbuttonActionPerformed(evt);
            }
        });

        bangtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sex", "PhoneNumber", "Address", "Hours of Use", "Total Amount"
            }
        ));
        bangtable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bangtable.setShowGrid(false);
        jScrollPane1.setViewportView(bangtable);

        jLabel7.setFont(new java.awt.Font("SF Mono", 2, 12)); // NOI18N
        jLabel7.setText("Sex:");

        buttonGroup1.add(namradio);
        namradio.setSelected(true);
        namradio.setText("Male");

        buttonGroup1.add(nuradio);
        nuradio.setText("Female");

        jButton1.setText("Refesh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thembutton)
                                .addGap(18, 18, 18)
                                .addComponent(suabutton)
                                .addGap(18, 18, 18)
                                .addComponent(xoabutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timkiembutton)
                                .addGap(18, 18, 18)
                                .addComponent(tinhtienbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thoatbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tentextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sdttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel3)
                                        .addGap(49, 49, 49)))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sogiosudungtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(diachitextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(namradio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nuradio)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sogiosudungtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tentextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diachitextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(namradio)
                    .addComponent(nuradio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thembutton)
                    .addComponent(suabutton)
                    .addComponent(xoabutton)
                    .addComponent(timkiembutton)
                    .addComponent(tinhtienbutton)
                    .addComponent(thoatbutton)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sogiosudungtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sogiosudungtextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sogiosudungtextfieldActionPerformed

    private void thembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thembuttonActionPerformed
        // TODO add your handling code here:
        
        String ten = JOptionPane.showInputDialog("Name");
        String gioitinh = JOptionPane.showInputDialog("Sex");
        String sdt = JOptionPane.showInputDialog("PhoneNumber");
        String diachi = JOptionPane.showInputDialog("Address");
        String sogiosudung = JOptionPane.showInputDialog("Hours of Use");
        
        int sotienmoigio = 5000;
        double x = sotienmoigio*Double.parseDouble(sogiosudung);
        DefaultTableModel model = (DefaultTableModel) bangtable.getModel();
        model.addRow( new Object[]{model.getRowCount()+1,ten,gioitinh,sdt,diachi,sogiosudung,x});
        bangtable.setModel(model);
        JOptionPane.showMessageDialog(rootPane, " Add success !");
    }//GEN-LAST:event_thembuttonActionPerformed

    private void xoabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) bangtable.getModel();
        int xoa = bangtable.getSelectedRow();
        if(xoa!=-1){
            model.removeRow(xoa);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Please select 1 row to delete");
        }
        JOptionPane.showMessageDialog(rootPane, "Delete success!");
    }//GEN-LAST:event_xoabuttonActionPerformed

    private void tinhtienbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhtienbuttonActionPerformed
        // TODO add your handling code here:
        String sex = "";
        if(namradio.isSelected()){
            sex+="Male";}
        if(nuradio.isSelected()){
            sex+="Female";}
        String sogiosudung = sogiosudungtextfield.getText();
        if(sogiosudung.isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Please Enter Hours of Use!");
            return ;
        }
        String name = tentextfield.getText();
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Please Enter Name!");
            return ;
        }
        String sdt =sdttextfield.getText();
        if(sdt.isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Please Enter phoneNumber!");
            return ;
        }
        
        String diachi = diachitextfield.getText();
        if(diachi.isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Please Enter Address!");
            return ;
        }
        int giatienmoigio = 5000;
        
        
        double x = giatienmoigio * Double.parseDouble(sogiosudung);
        DefaultTableModel model = (DefaultTableModel) bangtable.getModel();
        model.addRow(new Object[]{model.getRowCount()+1,name,sex,sdt,diachi,sogiosudung,x});
        bangtable.setModel(model);
        



    }//GEN-LAST:event_tinhtienbuttonActionPerformed

    private void thoatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatbuttonActionPerformed
       
        // TODO add your handling code here:
        System.exit(0);
       
    }//GEN-LAST:event_thoatbuttonActionPerformed
    private void lammoi(){
    sogiosudungtextfield.setText("");
    tentextfield.setText("");
    sdttextfield.setText("");
    diachitextfield.setText("");
    
    
    }
    private void timkiembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiembuttonActionPerformed
        // TODO add your handling code here:
        String timkiemid = JOptionPane.showInputDialog("Please enter the ID to search");
        if(timkiemid!=null){
        DefaultTableModel model = (DefaultTableModel) bangtable.getModel();
        boolean found = false ;
        for(int i=0; i<model.getRowCount();i++){
            String id = model.getValueAt(i, 0).toString();
            if(id.equals(timkiemid)){
                bangtable.setRowSelectionInterval(i, i);
                found = true;
                break;
            }
        }
        if(found){
            JOptionPane.showMessageDialog(rootPane, "ID found "+timkiemid);
        }
        else{
    JOptionPane.showMessageDialog(rootPane, "ID not found "+timkiemid);
}
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Please enter the ID to search");
        }
    
    }//GEN-LAST:event_timkiembuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lammoi();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void suabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) bangtable.getModel();
        int sua = bangtable.getSelectedRow();
        if(sua!=-1){
            int sotienmoigio = 5000;
          String ten = bangtable.getValueAt(sua,1).toString();
            String gt = bangtable.getValueAt(sua,2).toString();
            String sdt = bangtable.getValueAt(sua,3).toString();
            String diachi = bangtable.getValueAt(sua,4).toString();
            String sogiosudung = bangtable.getValueAt(sua,5).toString();
            
            String newten = JOptionPane.showInputDialog("Please enter a new name",ten);
            String newgt = JOptionPane.showInputDialog("Please enter a new gender",gt);
            String newsdt = JOptionPane.showInputDialog("Please enter new phone number",sdt);
            String newdiachi = JOptionPane.showInputDialog("Please enter a new address",diachi);
            String newsogiosudung = JOptionPane.showInputDialog("Please enter new access hours",sogiosudung);
          
            bangtable.setValueAt(newten, sua,1);
            bangtable.setValueAt(newgt, sua,2);
            bangtable.setValueAt(newsdt, sua,3);
            bangtable.setValueAt(newdiachi, sua,4);
            bangtable.setValueAt(newsogiosudung, sua,5);
            double x = sotienmoigio*Double.parseDouble(newsogiosudung);
            bangtable.setValueAt(x, sua,5 );
            JOptionPane.showMessageDialog(rootPane, "Successfully fixed!");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Please enter and select 1 row to edit!");
        }
    
        
    }//GEN-LAST:event_suabuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangtable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diachitextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton namradio;
    private javax.swing.JRadioButton nuradio;
    private javax.swing.JTextField sdttextfield;
    private javax.swing.JTextField sogiosudungtextfield;
    private javax.swing.JButton suabutton;
    private javax.swing.JTextField tentextfield;
    private javax.swing.JButton thembutton;
    private javax.swing.JButton thoatbutton;
    private javax.swing.JButton timkiembutton;
    private javax.swing.JButton tinhtienbutton;
    private javax.swing.JButton xoabutton;
    // End of variables declaration//GEN-END:variables
}
